### ISSUE TITLE
Fix failing tests draft-04/06, update schema usage

### ISSUE THREAD

**Issue by korzio** [korzio/djv#78]
```gherkin
Given a draft-04/06 meta schema update
When running unit tests
Then 17? tests are failing
```

https://github.com/ebdrup/json-schema-benchmark/pull/37

- [x] Understand the meta schema changes
- [x] Use schema from git repository. Now the schema is taken from npm dependency, and it's not updated anymore
- [x] Fix failing djv tests

Links:
- https://github.com/ebdrup/json-schema-benchmark/pull/37#issuecomment-480858664

Test branch:
- https://github.com/korzio/djv/compare/78-manual-schema-update?expand=1

---

Most tests are failing because of `\\` in the schema ids

```
SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at restore (/Users/RD25XO/Developer/schema/djv/lib/utils/template.js:124:15)
    at generate (/Users/RD25XO/Developer/schema/djv/lib/utils/state.js:50:10)
    at Environment.addSchema (/Users/RD25XO/Developer/schema/djv/lib/djv.js:90:11)
    at Object.validate (/Users/RD25XO/Developer/schema/djv/test/json-schema-test-suite.js:23:13)
    at doTest (/Users/RD25XO/Developer/schema/djv/node_modules/json-schema-test/index.js:79:43)
    at UserContext.<anonymous> (/Users/RD25XO/Developer/schema/djv/node_modules/json-schema-test/index.js:66:30)
    at attempt (/Users/RD25XO/Developer/schema/djv/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4478:46)
    at QueueRunner.run (/Users/RD25XO/Developer/schema/djv/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4402:20)
    at QueueRunner.execute (/Users/RD25XO/Developer/schema/djv/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4384:10)
result: false
expected:  true
errors: [ 'Invalid or unexpected token' ]
FSyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at restore (/Users/RD25XO/Developer/schema/djv/lib/utils/template.js:124:15)
    at generate (/Users/RD25XO/Developer/schema/djv/lib/utils/state.js:50:10)
    at Environment.addSchema (/Users/RD25XO/Developer/schema/djv/lib/djv.js:90:11)
    at Object.validate (/Users/RD25XO/Developer/schema/djv/test/json-schema-test-suite.js:23:13)
    at doTest (/Users/RD25XO/Developer/schema/djv/node_modules/json-schema-test/index.js:79:43)
    at UserContext.<anonymous> (/Users/RD25XO/Developer/schema/djv/node_modules/json-schema-test/index.js:66:30)
    at attempt (/Users/RD25XO/Developer/schema/djv/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4478:46)
    at QueueRunner.run (/Users/RD25XO/Developer/schema/djv/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4402:20)
    at QueueRunner.execute (/Users/RD25XO/Developer/schema/djv/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4384:10)
```

**Comment by korzio** [comment]
- [ ] Check how it is implemented in alternative json-schema validators

**Comment by korzio** [comment]
Thanks @openself !
Starting to release the fix - https://github.com/korzio/djv/issues/81
